# Generated by Django 2.2.20 on 2024-12-17 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import public_entities.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEntitiesFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.TextField()),
                ('file', models.FileField(upload_to=public_entities.models.public_entities_file_path)),
                ('import_report', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
