# Generated by Django 2.2.20 on 2025-06-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicentity',
            name='functiongroup1',
            field=models.CharField(blank=True, choices=[('General public services', 'General public services'), ('Economic development', 'Economic development'), ('Learning and culture', 'Learning and culture'), ('Social development', 'Social development'), ('Peace and security', 'Peace and security'), ('Community development', 'Community development'), ('Health', 'Health')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publicentity',
            name='pfma',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3A', '3A'), ('3B', '3B'), ('Not listed', 'Not listed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='publicentityexpenditure',
            name='functiongroup2',
            field=models.CharField(blank=True, choices=[('General public services', 'General public services'), ('Economic development', 'Economic development'), ('Learning and culture', 'Learning and culture'), ('Social development', 'Social development'), ('Peace and security', 'Peace and security'), ('Community development', 'Community development'), ('Health', 'Health')], max_length=200, null=True),
        ),
    ]
