# Generated by Django 2.2.20 on 2026-05-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_entities', '0002_auto_20250617_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicentity',
            options={'verbose_name_plural': 'public entities'},
        ),
        migrations.AddField(
            model_name='publicentityexpenditure',
            name='financialYear',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='publicentity',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='publicentity',
            name='amount',
        ),
    ]
