# Generated by Django 2.2.20 on 2025-03-11 08:03

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=1024)),
                ('dataset_title', models.CharField(max_length=1024)),
                ('document_type', models.CharField(max_length=50)),
                ('document_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=200, populate_from='name')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteDocument', to='budgetportal.Department')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
