# Generated by Django 2.2.20 on 2025-03-11 13:25

import autoslug.fields
import budgetportal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0002_votedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteDocumentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=budgetportal.models.datasets_file_path)),
            ],
        ),
        migrations.AlterField(
            model_name='votedocument',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=200, populate_from='dataset_name'),
        ),
    ]
