# Generated by Django 2.2.20 on 2025-03-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0003_auto_20250311_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='votedocument',
            name='financial_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='votedocument',
            name='government',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
