# Generated by Django 2.2.20 on 2025-03-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0004_auto_20250311_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votedocument',
            name='financial_year',
        ),
        migrations.AddField(
            model_name='votedocument',
            name='financialYear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voteDocument', to='budgetportal.FinancialYear'),
        ),
    ]
