# Generated by Django 2.2.20 on 2025-03-11 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0005_auto_20250311_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votedocument',
            name='government',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voteDocument', to='budgetportal.Government'),
        ),
    ]
