# Generated by Django 2.2.20 on 2025-06-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0006_auto_20250311_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureProjectImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/infrastructure_imports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
