# Generated by Django 2.2.20 on 2025-08-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0007_infrastructureprojectimportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetcategory',
            name='type',
            field=models.CharField(choices=[('Original Budget', 'Original Budget'), ('Adjusted Budget', 'Adjusted Budget')], default='Original Budget', max_length=50),
        ),
    ]
