# Generated by Django 2.2.20 on 2024-11-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0007_dataset_province'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatasetCategories',
            new_name='DatasetCategory',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Dimension',
        ),
        migrations.RenameModel(
            old_name='GovernmentFunctions',
            new_name='GovernmentFunction',
        ),
        migrations.RenameModel(
            old_name='Organisations',
            new_name='Organisation',
        ),
        migrations.RenameModel(
            old_name='Dimensions',
            new_name='Tag',
        ),
    ]
