# Generated by Django 2.2.20 on 2026-05-27 10:48

import budgetportal.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0008_datasetcategory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetvsactualnationaldata',
            name='budgetYear',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetvsactualprovincialdata',
            name='budgetYear',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='consolidationdata',
            name='budgetYear',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='datasetupload',
            name='financialYear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datasetUpload', to='budgetportal.FinancialYear'),
        ),
        migrations.AddField(
            model_name='enedata',
            name='budgetYear',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='epredata',
            name='budgetYear',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='votedocument',
            name='dataset_category',
            field=models.ForeignKey(default=budgetportal.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, to='budgetportal.DatasetCategory'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dimensions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetportal.Dimension'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='government_functions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetportal.GovernmentFunction'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='province',
            field=models.CharField(default='South Africa', max_length=1024),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetportal.Tag'),
        ),
        migrations.AlterField(
            model_name='datasetresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=budgetportal.models.resources_file_path),
        ),
        migrations.AlterField(
            model_name='datasetresource',
            name='format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'XLSX'), ('Doc', 'Doc'), ('XML', 'XML'), ('CSV', 'CSV'), ('Audio / Video', 'Audio / Video'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='datasetresource',
            name='path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='datasetupload',
            name='file',
            field=models.FileField(upload_to=budgetportal.models.resources_file_path),
        ),
        migrations.AlterField(
            model_name='datasetupload',
            name='type',
            field=models.CharField(choices=[('AENE', 'AENE'), ('ENE', 'ENE'), ('EPRE', 'EPRE'), ('Budget-vs-Actual-National', 'Budget-vs-Actual-National'), ('Budget-vs-Actual-Provincial', 'Budget-vs-Actual-Provincial'), ('Consolidation', 'Consolidation')], max_length=255),
        ),
        migrations.AlterField(
            model_name='epredata',
            name='functionGroup2',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
