# Generated by Django 2.2.20 on 2024-11-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0008_auto_20241107_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='dataset_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budgetportal.DatasetCategory'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dimensions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetportal.Dimension'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetportal.Tag'),
        ),
    ]
