# Generated by Django 2.2.20 on 2026-05-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0009_auto_20260527_1048'),
    ]

    operations = [

    ]
