# Generated by Django 2.2.20 on 2026-05-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0010_aenedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AENEData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteNumber', models.IntegerField()),
                ('department', models.CharField(max_length=1024)),
                ('progNumber', models.IntegerField()),
                ('programme', models.CharField(max_length=1024)),
                ('subprogNumber', models.CharField(max_length=1024)),
                ('subprogramme', models.CharField(max_length=1024)),
                ('economicClassification1', models.CharField(max_length=1024)),
                ('economicClassification2', models.CharField(max_length=1024)),
                ('economicClassification3', models.CharField(max_length=1024)),
                ('economicClassification4', models.CharField(max_length=1024)),
                ('economicClassification5', models.CharField(max_length=1024)),
                ('financialYear', models.CharField(max_length=1024)),
                ('budgetPhase', models.CharField(max_length=1024)),
                ('budgetYear', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('amountKind', models.CharField(max_length=1024)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
