# Generated by Django 2.2.20 on 2024-11-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0011_auto_20241108_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetresource',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgetportal.Dataset'),
        ),
    ]
