# Generated by Django 2.2.20 on 2026-05-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0011_aenedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetvsactualprovincialdata',
            name='functionGroup1',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
