# Generated by Django 2.2.20 on 2024-11-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0012_auto_20241108_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='short_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='datasetcategory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='datasetresource',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='governmentfunction',
            name='description',
            field=models.TextField(),
        ),
    ]
