# Generated by Django 2.2.20 on 2024-11-08 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0013_auto_20241108_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetresource',
            name='dataset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='budgetportal.Dataset'),
        ),
    ]
