# Generated by Django 2.2.20 on 2024-11-11 14:15

import budgetportal.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0014_auto_20241108_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetresource',
            name='file',
            field=models.FileField(upload_to=budgetportal.models.resources_file_path),
        ),
        migrations.CreateModel(
            name='ENEData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteNumber', models.IntegerField()),
                ('progNumber', models.IntegerField()),
                ('programme', models.CharField(max_length=1024)),
                ('subprogNumber', models.CharField(max_length=1024)),
                ('subprogramme', models.CharField(max_length=1024)),
                ('economicClassification1', models.CharField(max_length=1024)),
                ('economicClassification2', models.CharField(max_length=1024)),
                ('economicClassification3', models.CharField(max_length=1024)),
                ('economicClassification4', models.CharField(max_length=1024)),
                ('economicClassification5', models.CharField(max_length=1024)),
                ('functionGroup1', models.CharField(max_length=1024)),
                ('financialYear', models.CharField(max_length=1024)),
                ('budgetPhase', models.CharField(max_length=1024)),
                ('value', models.IntegerField()),
                ('selectedFinancialYear', models.IntegerField()),
                ('file', models.FileField(upload_to=budgetportal.models.datasets_file_path)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='budgetportal.Department')),
            ],
        ),
    ]
