# Generated by Django 2.2.20 on 2024-11-12 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgetportal', '0016_auto_20241111_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='enedataupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='enedataupload',
            name='task_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enedataupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='enedataupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
