# Generated by Django 2.2.20 on 2024-11-13 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0017_auto_20241112_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enedata',
            name='file',
        ),
        migrations.AddField(
            model_name='enedataupload',
            name='selectedFinancialYear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budgetportal.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='enedata',
            name='department',
            field=models.CharField(max_length=1024),
        ),
    ]
