# Generated by Django 2.2.20 on 2024-11-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0019_auto_20241113_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enedata',
            name='selectedFinancialYear',
            field=models.CharField(max_length=1024),
        ),
    ]
