# Generated by Django 2.2.20 on 2024-11-13 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0020_auto_20241113_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enedata',
            name='selectedFinancialYear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enedataupload',
            name='selectedFinancialYear',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetportal.FinancialYear'),
        ),
    ]
