# Generated by Django 2.2.20 on 2024-11-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0021_auto_20241113_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enedata',
            name='selectedFinancialYear',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
