# Generated by Django 2.2.20 on 2024-11-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0025_auto_20241114_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='enedata',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
