# Generated by Django 2.2.20 on 2024-11-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0026_enedata_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functionGroup', models.CharField(max_length=400)),
                ('economicClassification2', models.CharField(max_length=400)),
                ('economicClassification3', models.CharField(max_length=400)),
                ('financialYear', models.CharField(max_length=400)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
