# Generated by Django 2.2.20 on 2024-11-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0028_epredata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetupload',
            name='type',
            field=models.CharField(choices=[('ENE', 'ENE'), ('EPRE', 'EPRE'), ('Budget-vs-Actual-National', 'Budget-vs-Actual-National'), ('Budget-vs-Actual-Provincial', 'Budget-vs-Actual-Provincial'), ('Consolidation', 'Consolidation')], max_length=255),
        ),
    ]
