# Generated by Django 2.2.20 on 2024-11-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0029_auto_20241114_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetVSActualNationalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governmenting', models.CharField(max_length=400)),
                ('voteNumber', models.IntegerField()),
                ('department', models.CharField(max_length=400)),
                ('progNumber', models.IntegerField()),
                ('programme', models.CharField(max_length=400)),
                ('subprogNumber', models.CharField(max_length=400)),
                ('subprogramme', models.CharField(max_length=400)),
                ('economicClassification1', models.CharField(max_length=400)),
                ('economicClassification2', models.CharField(max_length=400)),
                ('economicClassification3', models.CharField(max_length=400)),
                ('economicClassification4', models.CharField(max_length=400)),
                ('economicClassification5', models.CharField(max_length=400)),
                ('functionGroup1', models.CharField(max_length=400)),
                ('financialYear', models.CharField(max_length=400)),
                ('budgetPhase', models.CharField(max_length=400)),
                ('amountKind', models.CharField(max_length=400)),
                ('value', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetVSActualProvincialData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governmenting', models.CharField(max_length=400)),
                ('voteNumber', models.IntegerField()),
                ('department', models.CharField(max_length=400)),
                ('progNumber', models.IntegerField()),
                ('programme', models.CharField(max_length=400)),
                ('subprogNumber', models.CharField(max_length=400)),
                ('subprogramme', models.CharField(max_length=400)),
                ('economicClassification1', models.CharField(max_length=400)),
                ('economicClassification2', models.CharField(max_length=400)),
                ('economicClassification3', models.CharField(max_length=400)),
                ('economicClassification4', models.CharField(max_length=400)),
                ('economicClassification5', models.CharField(max_length=400)),
                ('functionGroup1', models.CharField(max_length=400)),
                ('financialYear', models.CharField(max_length=400)),
                ('budgetPhase', models.CharField(max_length=400)),
                ('amountKind', models.CharField(max_length=400)),
                ('value', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
            ],
        ),
    ]
