# Generated by Django 2.2.20 on 2024-11-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0030_budgetvsactualnationaldata_budgetvsactualprovincialdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetvsactualnationaldata',
            old_name='governmenting',
            new_name='government',
        ),
        migrations.RenameField(
            model_name='budgetvsactualprovincialdata',
            old_name='governmenting',
            new_name='government',
        ),
    ]
