# Generated by Django 2.2.20 on 2024-12-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0031_auto_20241114_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenuitem',
            name='highlight_as_new',
            field=models.BooleanField(default=False),
        ),
    ]
