services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_server
    ports:
      - "1433:1433" # Maps the container's port 1433 to the host's port 1433
    environment:
      SA_PASSWORD: "@Budgetportal51" # Replace with a strong password
      ACCEPT_EULA: "Y"                   # Accept the SQL Server EULA
      MSSQL_PID: "Developer"             # Use Developer edition, free for development
    volumes:
      - mssql_data:/var/opt/mssql  
           # Persistent storage for SQL Server data
  app:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - TAG_MANAGER_ID
      - DJANGO_DEBUG_TOOLBAR
      - SOLR_URL=http://solr:8983/solr/budgetportal
      - DEBUG_CACHE
      - DJANGO_WHITENOISE_AUTOREFRESH=TRUE
      - PORT=8000
      #- GUNICORN_WORKERS_ARG=1 # Useful for testing start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - solr
      - mssql
    links:
      - selenium

  # Should be same as app except for command and ports
  worker:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
    command: python manage.py qcluster
    environment:
      - DJANGO_DEBUG_TOOLBAR=${DJANGO_DEBUG_TOOLBAR:-False}
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - SOLR_URL=http://solr:8983/solr/budgetportal
    volumes:
      - .:/app
    depends_on:
      - solr

  solr:
    build: "https://github.com/vulekamali/solr-dokku.git"
    image: budgetportal-solr
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/opt/solr/server/solr/budgetportal/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  selenium:
    image: selenium/standalone-chrome:3.141
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900
    shm_size: '2gb'
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=

volumes:
  solr-data:
  mssql_data:
    driver: local
