# Generated by Django 2.2.20 on 2024-10-30 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import performance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgetportal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EQPRSFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('task_id', models.TextField()),
                ('file', models.FileField(upload_to=performance.models.eqprs_file_path)),
                ('import_report', models.TextField()),
                ('num_imported', models.IntegerField(default=0, null=True, verbose_name='Number of rows we could import')),
                ('num_not_imported', models.IntegerField(default=0, null=True, verbose_name='Number of rows we could not import')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('indicator_name', models.TextField()),
                ('q1_target', models.TextField(blank=True)),
                ('q1_actual_output', models.TextField(blank=True)),
                ('q1_deviation_reason', models.TextField(blank=True)),
                ('q1_corrective_action', models.TextField(blank=True)),
                ('q1_national_comments', models.TextField(blank=True)),
                ('q1_otp_comments', models.TextField(blank=True)),
                ('q1_dpme_coordinator_comments', models.TextField(blank=True)),
                ('q1_treasury_comments', models.TextField(blank=True)),
                ('q2_target', models.TextField(blank=True)),
                ('q2_actual_output', models.TextField(blank=True)),
                ('q2_deviation_reason', models.TextField(blank=True)),
                ('q2_corrective_action', models.TextField(blank=True)),
                ('q2_national_comments', models.TextField(blank=True)),
                ('q2_otp_comments', models.TextField(blank=True)),
                ('q2_dpme_coordinator_comments', models.TextField(blank=True)),
                ('q2_treasury_comments', models.TextField(blank=True)),
                ('q3_target', models.TextField(blank=True)),
                ('q3_actual_output', models.TextField(blank=True)),
                ('q3_deviation_reason', models.TextField(blank=True)),
                ('q3_corrective_action', models.TextField(blank=True)),
                ('q3_national_comments', models.TextField(blank=True)),
                ('q3_otp_comments', models.TextField(blank=True)),
                ('q3_dpme_coordinator_comments', models.TextField(blank=True)),
                ('q3_treasury_comments', models.TextField(blank=True)),
                ('q4_target', models.TextField(blank=True)),
                ('q4_actual_output', models.TextField(blank=True)),
                ('q4_deviation_reason', models.TextField(blank=True)),
                ('q4_corrective_action', models.TextField(blank=True)),
                ('q4_national_comments', models.TextField(blank=True)),
                ('q4_otp_comments', models.TextField(blank=True)),
                ('q4_dpme_coordinator_comments', models.TextField(blank=True)),
                ('q4_treasury_comments', models.TextField(blank=True)),
                ('annual_target', models.TextField(blank=True)),
                ('annual_aggregate_output', models.TextField(blank=True)),
                ('annual_pre_audit_output', models.TextField(blank=True)),
                ('annual_deviation_reason', models.TextField(blank=True)),
                ('annual_corrective_action', models.TextField(blank=True)),
                ('annual_otp_comments', models.TextField(blank=True)),
                ('annual_national_comments', models.TextField(blank=True)),
                ('annual_dpme_coordinator_comments', models.TextField(blank=True)),
                ('annual_treasury_comments', models.TextField(blank=True)),
                ('annual_audited_output', models.TextField(blank=True)),
                ('sector', models.TextField(blank=True)),
                ('programme_name', models.TextField(blank=True)),
                ('subprogramme_name', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('annually', 'Annually'), ('quarterly', 'Quarterly')], max_length=9)),
                ('type', models.TextField(blank=True)),
                ('subtype', models.TextField(blank=True)),
                ('mtsf_outcome', models.TextField(blank=True)),
                ('cluster', models.TextField(blank=True)),
                ('uid', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('content_search', models.TextField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_values', to='budgetportal.Department')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_values', to='performance.EQPRSFileUpload')),
            ],
            options={
                'verbose_name_plural': 'Indicator',
            },
        ),
        migrations.CreateModel(
            name='EQPRSDepartmentAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('alias', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetportal.Department')),
            ],
            options={
                'verbose_name_plural': 'Eqprs department aliases',
            },
        ),
    ]
