# Generated by Django 2.2.20 on 2024-11-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={},
        ),
        migrations.RemoveField(
            model_name='eqprsdepartmentalias',
            name='name',
        ),
        migrations.RemoveField(
            model_name='eqprsfileupload',
            name='name',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='name',
        ),
    ]
