# Generated by Django 2.2.20 on 2025-05-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqprsfileupload',
            name='report_type',
            field=models.CharField(choices=[('Provincial', 'Provincial Institutions Oversight Performance Report'), ('National', 'National Institutions Oversight Performance Report')], default='national', max_length=50, verbose_name='Report Type'),
        ),
    ]
