# Generated by Django 2.2.20 on 2025-05-12 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetportal', '0006_auto_20250311_2053'),
        ('performance', '0002_eqprsfileupload_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqprsfileupload',
            name='financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EQPRSFileUploads', to='budgetportal.FinancialYear'),
        ),
    ]
